title: V&N Team

navbar: ./config/navbar.yml

page:
  index: ./config/index.yml
  achievements: ./config/achievements.md
  members: ./config/members.yml
  join: ./config/join.md
  vnctf: ./config/vnctf.md

footer:
  -
    - Copyright (c) [V&N Team](https://github.com/vn-sec)
    - CDN Hosted on [LightXi](https://www.lightxi.com/)
  - '[蜀ICP备2024116417号-1](http://beian.miit.gov.cn/)'
