title: V&N Team

navbar: ./config/navbar.yml

page:
  index: ./config/index.yml
  achievements: ./config/achievements.md
  members: ./config/members.yml
  join: ./config/join.md

footer:
  copyright: Copyright (c) [V&N Team](https://github.com/vn-sec)
  beian: "[蜀ICP备2024116417号-1](https://beian.miit.gov.cn/)"
