title: Members
subtitle: Want to join us? [Click here](~/join).

content:
  # - name:        # name (required)
  #   avatar:      # link for avatar image
  #   tags: Web    # array or string
  #   description: # markdown supported
  #   link:        # link to personal website or blog

  - name: unknown
    avatar: https://unk-blog-image.oss-cn-shenzhen.aliyuncs.com/unknown.jpg
    tags: [ Leader, Web ]
    description: "真正的大师，永远都怀着一颗学徒的心"
    link: https://unk.org.cn
    status: active

  - name: Qanux
    avatar: https://avatars.githubusercontent.com/u/126745796
    tags: Pwn
    description: "勇往直前是我唯一的退路👊"
    link: https://9anux.org
    status: former

  - name: 0xA1pha
    avatar: https://neuqcsa.cn/static/images/ico/0xA1pha.png
    tags: Reverse
    description: "一个 23 级的菜菜逆向手"
    status: active

  - name: C_LBY
    avatar: https://blog-1258572842.cos.ap-nanjing.myqcloud.com/obsidian/202408142342917.png
    tags: Pwn
    description: "我们联合，形成两面包夹芝士！"
    link: https://c-lby.top
    status: active

  - name: Chimedal
    avatar: https://pica.zhimg.com/80/v2-b952a99e6919cf6f56ad4d493517fe3c_1440w.jpeg?source=d16d100b
    tags: Web
    description: "Just for fun!"
    link: https://Chimedal.github.io
    status: active

  - name: Aecous
    avatar: https://q1.qlogo.cn/g?b=qq&nk=2894248907&s=160
    tags: Web
    description: "Prove yourself"
    link: https://aecous.github.io/
    status: active

  - name: PangBai
    avatar: https://thirdqq.qlogo.cn/g?b=oidb&k=vE3usuUH5ZeNhREOjiaq8tQ&s=640&t=1606030712
    tags: Reverse
    description: "Meow? meow meow"
    link: https://pangbai.work
    status: active

  - name: CH13hh
    avatar: https://q1.qlogo.cn/g?b=qq&nk=2804894416&s=160
    tags: Pwn
    description: "The best way to predict the future is to create it."
    link: https://ch13hh.github.io/
    status: active

  - name: gets
    avatar: https://c.img.dasctf.com/LightPicture/2024/08/ab868415fdfc7ff5.jpg
    tags: Pwn
    description: "好饿啊，早知道不学 pwn 了"
    link: https://www.getspwn.xyz
    status: active

  - name: ph0ebus
    avatar: https://c.img.dasctf.com/LightPicture/2024/08/ac126286f0762f42.jpg
    tags: Web
    description: "Study On Web Security && Penetration Testing && Java Security, no hack no fun!"
    link: http://ph0ebus.cn/
    status: active

  - name: cyi
    avatar: https://q1.qlogo.cn/g?b=qq&nk=1873287169&s=160
    tags: Misc
    description: "梧高凤必至_花香蝶自来"
    link: https://www.cnblogs.com/xhzccy
    status: active

  - name: Infernity
    avatar: http://q1.qlogo.cn/g?b=qq&nk=1366400792&s=160
    tags: [ Misc, Web ]
    description: "爱玩恐怖游戏的 Web 苦手"
    link: https://infernity.top
    status: active

  - name: yixinBC
    avatar: https://c.img.dasctf.com/LightPicture/2024/08/c6a64c00f2c066f8.jpg
    tags: Misc
    description: "超级无敌巨菜浑水摸鱼手"
    link: https://blog.buyix.in
    status: active

  - name: 0xAkyOI
    avatar: https://blog.akyuu.space/images/avatar.jpg
    tags: Pwn
    description: "C🤡NST unsigned int i = π;"
    link: https://blog.akyuu.space/
    status: former

  - name: ATRI
    avatar: https://c.img.dasctf.com/LightPicture/2024/08/ec2102768f9741c8.jpg
    tags: Reverse
    description: "一个摸鱼选手"
    # link:
    status: active

  - name: g01den
    avatar: https://q1.qlogo.cn/g?b=qq&nk=2082045221&s=160
    tags: Web
    description: "一个喜欢玩儿音游的似宅"
    link: https://g01den1.github.io/
    status: active

  - name: f1ngy3
    avatar: https://q1.qlogo.cn/g?b=qq&nk=2993669760&s=160
    tags: Reverse
    description: "古希腊掌管睡觉の神"
    # link:
    status: active

  - name: 3cly
    avatar: https://q1.qlogo.cn/g?b=qq&nk=987623364&s=160
    tags: Reverse
    description: "佛系逆向菜狗"
    link: https://3cly.github.io
    status: active

  - name: kw17
    avatar: https://c.img.dasctf.com/LightPicture/2024/08/cb27e0ee564ba6ac.jpg
    tags: Reverse
    description: "其实我的本体，可能是一只会阿巴阿巴的卡皮巴拉"
    # link:
    status: active

  - name: korey0sh1
    avatar: https://cdn.jsdelivr.net/gh/korey0sh1/clouding@master/data/b_e471dd030d1baa14d30360280e09e32a.jpg
    tags: Pwn
    description: "试图学会 Web 的屑 korey"
    link: https://korey0sh1.fun
    status: active

  - name: LiBr
    avatar: https://gravatar.loli.net/avatar/27c24bc48abf694631bb15836511d135?s=200&d=mp&r=g
    tags: Misc
    description: "Nothing here."
    link: https://nvme0n1p.dev
    status: active

  - name: WAHAHA
    avatar: https://gngtwhh.space/img/avatar.jpg
    tags: Reverse
    description: "一个爱折腾的蒟蒻"
    link: https://gngtwhh.github.io/
    status: active

  - name: l4n
    avatar: https://q1.qlogo.cn/g?b=qq&nk=862757556&s=160
    tags: Reverse
    description: "半吊子 RE 人"
    link: https://lancerorz.top
    status: former

  - name: JJKK
    avatar: https://q1.qlogo.cn/g?b=qq&nk=2311834720&s=160
    tags: Reverse
    description: "CTF RE players, determined to become a binary player."
    # link:
    status: active

  - name: 柚子
    avatar: https://unk-blog-image.oss-cn-shenzhen.aliyuncs.com/youzi.jpg
    tags: Crypto
    description: "因为热爱，所以长远"
    # link:
    status: active

  - name: N1gh7ma12e
    avatar: https://q1.qlogo.cn/g?b=qq&nk=1051667762&s=160
    tags: Crypto
    description: "密码小菜鸡一枚 QAQ"
    link: http://n1gh7ma12e.cn/
    status: active

  - name: Z1d10t
    avatar: https://q1.qlogo.cn/g?b=qq&nk=2081684790&s=160
    tags: Web
    description: "喜欢 Web 安全与渗透"
    link: https://z1d10t.fun/
    status: active

  - name: sekiro
    avatar: https://q1.qlogo.cn/g?b=qq&nk=3331308771&s=160
    tags: Pwn
    description: "Know a little pwn?"
    link: https://www.sekiro.love
    status: former

  - name: xianyuuuan
    avatar: https://s2.loli.net/2024/08/14/I25gQWbAmNTEHce.png
    tags: Reverse
    description: "有意思的优质咸鱼"
    link: https://xianyuuuan.space
    status: active

  - name: wd2711
    avatar: https://avatars.githubusercontent.com/u/88755653?s=40&v=4
    tags: Reverse
    description: "爱玩的菜鸡"
    link: https://wd-2711.tech
    status: active

  - name: Hur1k
    avatar: https://hur1k.github.io/img/avatar.jpg
    tags: Reverse
    description: "404 Error"
    link: https://hur1k.github.io/
    status: active

  - name: V3g3t4ble
    avatar: https://blog-1258572842.cos.ap-nanjing.myqcloud.com/obsidian/202408141510512.jpeg
    tags: Web
    description: "去码头整点 flag"
    link: https://www.imsb114514.cn/
    status: active

  - name: xswlhhh
    avatar: https://q1.qlogo.cn/g?b=qq&nk=2991796382&s=160
    tags: Pwn
    description: "分清大事和小事"
    link: https://yuque.com/xswlhhh/ctf
    status: active

  - name: 鱿鱼
    avatar: https://unk-blog-image.oss-cn-shenzhen.aliyuncs.com/the.jpg
    tags: Web
    description: "我是鱿鱼师傅，欢迎各位师傅和我扩列带带小弟"
    link: https://www.cnblogs.com/dleyi
    status: active


  - name: M4nd3l3y3v
    avatar: https://unk-blog-image.oss-cn-shenzhen.aliyuncs.com/abaed3e2a8d029d327e1cd2a12e73a8c.png
    tags: [ Misc, Web ]
    description: "Go and Hack,make my day!"
    # link:
    status: active

  - name: Mash1r0
    avatar: https://bu.dusays.com/2024/07/08/668b937ccb984.jpg
    tags: Web
    description: "你想要变成什么颜色？"
    link: https://mashiro726.github.io/
    status: active

  - name: AsaL1n
    avatar: https://asal1n.github.io/img/head.jpg
    tags: Web
    description: "why we need that?"
    link: https://asal1n.github.io/
    status: active

  - name: C3ngH
    avatar: https://c3ngh-blog.oss-cn-hangzhou.aliyuncs.com/img/C3ngH.jpg
    tags: Misc
    description: "广告位招租"
    link: https://c3ngh.top/
    status: active

  - name: Inkey
    avatar: https://avatars.githubusercontent.com/u/39005478?s=800
    tags: Pwn
    description: "可以打一辈子CTF吗"
    link: https://inkeyp.github.io/
    status: former

  - name: ZianTT
    avatar: https://q1.qlogo.cn/g?b=qq&nk=2508164094&s=160
    tags: [Pentesting, Web, Misc]
    description: "Trailblaze Tomorrow"
    status: former

  - name: LamentXU
    avatar: https://q1.qlogo.cn/g?b=qq&nk=1372449351&s=160
    tags: Web
    description: "Fly, broken wings"
    link: https://lamentxu.top/
    status: active

  - name: PuH4ck3rX
    avatar: https://puh4ck3rx.github.io/images/avatar.png
    tags: Pwn
    description: "Fight, protect wings"
    link: https://puh4ck3rx.github.io/
    status: active

  - name:  Liv
    avatar: https://q1.qlogo.cn/g?b=qq&nk=1319923129&s=160
    tags: Reverse
    description: Re and fun
    link: https://tkazer.github.io/
    status: former

  - name: q1uf3ng
    avatar: https://q1.qlogo.cn/g?b=qq&nk=2160789185&s=160
    tags: Web
    description: 幻想着自由的生活，如夏花般绚烂的诱惑
    link: https://x.com/q1uf3ng
    status: active

  - name: lianjin
    avatar: https://lianjinlll.cn/images/profilePicture.jpg
    description: hell0_w0r1d
    tags: Crypto
    link: https://lianjinlll.cn
    status: active

  - name: Jerrythepro123
    description: QWERTY
    tags: Pwn
    link: https://jerrythepro123.github.io
    status: active



